typography_spectrum: 0.10410752333700657
color:
  brandStrength: 0.8621908153872937
  lightness: 0.1812141053378582
  saturation: 0.5144241617526859
  rhythmicContrast: 0.0344491598661989
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.07653860258869827
name: Andrew Richard Mills
navigation:
  - name: My other version
    url: 'http://www.andrewrichardmills.co.uk'
    type: external
description: Just my world...
